#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_warn
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr contains
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_all
#' @importFrom dplyr if_any
#' @importFrom dplyr if_else
#' @importFrom dplyr lag
#' @importFrom dplyr lead
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice_max
#' @importFrom dplyr slice_min
#' @importFrom dplyr summarise
#' @importFrom dplyr tibble
#' @importFrom dplyr ungroup
#' @importFrom dplyr where
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_blank
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_viridis_c
#' @importFrom ggplot2 scale_color_viridis_d
#' @importFrom ggplot2 scale_colour_discrete
#' @importFrom ggplot2 scale_fill_discrete
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_datetime
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 vars
#' @importFrom lifecycle deprecated
#' @importFrom lubridate date
#' @importFrom lubridate hour
#' @importFrom purrr map
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom rlang .data
#' @importFrom rlang :=
#' @importFrom stringr str_extract
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom tidyr drop_na
#' @importFrom tidyr fill
#' @importFrom tidyr hoist
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr separate_wider_regex
#' @importFrom tidyr unnest
#' @importFrom tidyr unnest_wider
## usethis namespace: end
NULL
